config/routes.rb
Grammable::Application.routes.draw do
  devise_for :users
  root "grams#index"
  resources :grams do
    resources :comments, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gram
  belongs_to :user
end

app/models/gram.rb
class Gram < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :message, presence: true
  validates :picture, presence: true
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :grams
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def render_not_found(status=:not_found)
      render plain: "#{status.to_s.titleize} :(", status: status
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def create
    @gram = Gram.find_by_id(params[:gram_id])
    return render_not_found if @gram.blank?
    @gram.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private

 

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @grams = Gram.all
  end

  def new
    @gram = Gram.new
  end

  def create
    @gram = current_user.grams.create(gram_params)

    if @gram.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end

  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
  end

  def update
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user

    @gram.update_attributes(gram_params)
    if @gram.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
    @gram.destroy
    redirect_to root_path
  end


  private

  def gram_params
    params.require(:gram).permit(:message, :picture)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
  <h2>Edit Gram</h2>

  <%= simple_form_for @gram do |f| %>
    <%= f.input :message %>
    <%= f.input :picture %>
    <%= f.submit 'Update', class: 'my-btn' %>
  <% end %>

</div>

app/views/grams/index.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
  <% @grams.each do |gram| %>
  <div class="card">
    <div class="handle"><%= gram.user.email %></div>
    <%= image_tag gram.picture.url, class: 'img-fluid' %>
    <p>
      <%= gram.message %>
    </p>
     <div class="gram-actions float-right">
      <% if current_user && current_user == gram.user %>
        <%= link_to 'Edit', edit_gram_path(gram) %>
        <%= link_to 'Destroy', gram_path(gram), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </div>
    <br class="clear-fix" />
          <div class="comments">
        <h3>Comments</h3>
        <% gram.comments.each do |comment| %>
          <div class="comment">
            <span class="comment_handle">
              <%= comment.user.email %>
            </span>

            <%= comment.message %>
          </div>
        <% end %>
        <h4>Add a comment</h4>
        <%= simple_form_for Comment.new, url: gram_comments_path(gram) do |f| %>
          <%= f.input :message %>
          <%= f.submit 'Add Comment', class: 'my-btn' %>
        <% end %>
      </div>
  </div>
  <% end %>
</div>

app/views/grams/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">

  <h1>New Gram</h1>

  <%= simple_form_for @gram do |f| %>
    <%= f.input :message %>
    <%= f.input :picture %>
    <%= f.submit "Post!", class: 'my-btn' %>
  <% end %>

</div>

app/views/grams/show.html.erb
<%= @gram.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grammable</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
<div class="top-nav">
  <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
    <div class="brand float-left">
      Grammable
    </div>
    <div class="add float-right">
      <% if current_user %>
        Welcome, <%= current_user.email %>.
        <%= link_to "New Post", new_gram_path %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %>
        <%= link_to "Sign Up", new_user_registration_path %>
      <% end %>
    </div>

  </div>
  <br class="clear-fix" />
</div>
    <%= yield %>
  </body>
</html>